### ISSUE TITLE
beacon node doesn't have a parent in db with root --ropsten

### ISSUE THREAD

**Issue by basvlanat** [prysmaticlabs/prysm#10877]
# 💎 Issue
### Background
I used documentation [page](https://docs.prylabs.network/docs/next/install/install-with-docker/#downloading-the-prysm-docker-images) for run beacon node **v2.1.3-rc.3** in docker . 
### Description
I'm trying sync beacon node, for my geth node in the test network` --ropsten`. I only need it so that my geth node gets into the correct chain of blocks after [merge](https://blog.ethereum.org/2022/06/03/ropsten-merge-ttd/).
I'm running beacon node from docker, my docker-compose file:
```
version: '3.9'
services:
  beacon-test-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.1.3-rc.3
    hostname: beacon-test-node
    volumes:
      - "/mnt/data0/beacon-test-node/data1:/data"
      - "/mnt/data0/beacon-test-node/genesis1/genesis.ssz:/genesis/genesis.ssz"
    command:
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --http-web3provider=http://172.16.17.6:8550
      - --genesis-state=/genesis/genesis.ssz
      - --terminal-total-difficulty-override=50000000000000000
      - --ropsten
      - --accept-terms-of-use
    ports:
      - 4000:4000
      - 13000:13000 
      - 12000:12000/udp
```
But I get an error while syncing:

 ```
time="2022-06-14 12:11:04" level=info msg="Processing block batch of size 61 starting from  0x8f1a6d3e... 65536/106255 - estimated time remaining 9m46s" blocksPerSecond=69.5 peers=5 prefix=initial-sync
 time="2022-06-14 12:11:04" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x56531606c0bd5a8055c0592c2e6f822bb11e3453c3ab7f44a0e932e76b076117 (in processBatchedBlocks, slot=65536)" prefix=initial-sync
time="2022-06-14 12:11:06" level=info msg="Processing block batch of size 63 starting from  0x5f121470... 65088/106255 - estimated time remaining 9m52s" blocksPerSecond=69.5 peers=5 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="could not process block in batch: method not found: received an undefined ee error" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 50 starting from  0x7bc82575... 65152/106255 - estimated time remaining 13m11s" blocksPerSecond=52.0 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x7d3303ad6cf3dfbf55394fd50789a1616af25187984d3d56fd4fafc2f02694da (in processBatchedBlocks, slot=65152)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 49 starting from  0x4d81edfc... 65218/106255 - estimated time remaining 12m34s" blocksPerSecond=54.4 peers=4 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x8d4e14afa8f31605b80c317c64852b9d2c25f1770bd80e20c659f2eb977f7b9b (in processBatchedBlocks, slot=65218)" prefix=initial-sync
 time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 57 starting from  0x67aba47f... 65280/106255 - estimated time remaining 11m55s" blocksPerSecond=57.2 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xd99d8bd1860c47a1995458e09fa422ef7c42fed66575da26c17963e3d99af2e3 (in processBatchedBlocks, slot=65280)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 58 starting from  0x6bfc01f7... 65344/106255 - estimated time remaining 11m20s" blocksPerSecond=60.1 peers=4 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x83ac86c72af236e3ce1a02d9261132d4e9a84faf64e3806178e15afc35d91221 (in processBatchedBlocks, slot=65344)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 62 starting from  0x6bc69414... 65408/106255 - estimated time remaining 10m45s" blocksPerSecond=63.2 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xc374da4e750236af42eb4976412bfc1f96cbed3f07eac1938c42233c97c8442d (in processBatchedBlocks, slot=65408)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 63 starting from  0x19d6d017... 65472/106255 - estimated time remaining 10m14s" blocksPerSecond=66.4 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xedacd662531617166bc7f0480812010c258d411b8bba2d359310276ec9b7adc7 (in processBatchedBlocks, slot=65472)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 61 starting from  0x8f1a6d3e... 65536/106255 - estimated time remaining 9m46s" blocksPerSecond=69.5 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x56531606c0bd5a8055c0592c2e6f822bb11e3453c3ab7f44a0e932e76b076117 (in processBatchedBlocks, slot=65536)" prefix=initial-sync
 time="2022-06-14 12:11:10" level=info msg="Connected to new endpoint: http://172.16.17.6:8550" prefix=powchain

```
Please tell me what I'm doing wrong??
