### ISSUE TITLE
ERROR powchain: Could not connect to execution client endpoint error=Post "http://localhost:8551": dial tcp 127.0.0.1:8551: connect: connection refused...

### ISSUE THREAD

**Issue by klestrong** [prysmaticlabs/prysm#11414]
# 💎 Issue
Hi! 😄 

I’m getting connection refused messages for the execution client I’ve configured for Beacon.
```
ERROR powchain: Could not connect to execution client endpoint error=Post "http://localhost:8551": dial tcp 127.0.0.1:8551: connect: connection refused...
```
### Background

 Context and background information on the discussion...

### Description
My docker run command for Beacon (Prysm v3.1.0) is below:
```
docker run --rm -d -it -v /home/ubuntu/.eth2:/data -v /home/ubuntu/jwtsecret:/var/lib/jwtsecret -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --network=go-ethereum-v11023_default --name beacon-node asia.gcr.io/someimage/prysm/beacon-chain:v3.1.0 --datadir=/data --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --execution-endpoint=http://localhost:8551 --jwt-secret=/var/lib/jwtsecret/jwt2.hex --suggested-fee-recipient=0x90…05C2 --accept-terms-of-use
```
I’ve configured JWT token for both the Geth execution client and Beacon node.  Prylabs docs indicate the above error could be triggered by the JWT token if it’s done wrong.  I’ve had the execution client on a separate server sharing the same JWT token.  I’ve also run the Geth execution client and the Beacon on the same server referencing the same JWT token file as well as the same JWT token in separate files.  I’m running the Geth execution client in docker-compose as a separate server as well as on the same server as the Beacon node.

I produced the JWT token using the below command.
```
openssl rand -hex 32 | tr -d "\n" > "jwt.hex"
```
My Geth (go-eth v1.10.23) execution client docker-compose is below.
```
version: "3"
services:
  geth:
    image: ethereum/client-go:v1.10.23
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8551:8551"
      - "8546:8546"
    volumes:
      - ~/.geth:/geth
      - /home/ubuntu/jwtsecret:/var/lib/jwtsecret
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --http
      - --http.api
      - "eth,net,engine,web3"
      - --authrpc.jwtsecret
      - "/var/lib/jwtsecret/jwt.hex"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,engine,web3"
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --datadir
      - "/geth"
      - --syncmode=full
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```
When Geth execution client and Beacon are run on separate servers, I’ve checked the firewall and confirmed connectivity between both servers with ping, ssh and curl to the Geth server.  When Geth execution client and Beacon are on the same server, I’ve put them in the same docker network and run them in separate docker networks.

Any ideas what else I can do or what other information you need to help me get Beacon communicating with the Geth execution client?
![2022-09-07 11_29_20-ubuntu@prod-prysm-staking-cygnus_ ~_go-ethereum-v1 10 23](https://user-images.githubusercontent.com/102823326/188959406-86f69767-5b8f-4dc6-a519-1dd0ac513153.png)
![beacon redacted](https://user-images.githubusercontent.com/102823326/188960328-a0823bfc-5a35-4a90-a82e-0d4f7a14805f.png)
![Geth execution client](https://user-images.githubusercontent.com/102823326/188960624-89b87d35-9adc-4d30-8f42-d9e136c3a138.png)
![Prylabs troubleshoot](https://user-images.githubusercontent.com/102823326/188960717-d3a59c3d-ba36-4196-8bd6-7f41595a3fe3.png)

**Comment by prestonvanloon** [comment]
This seems like a docker-compose issue. I suspect that the containers are not running with the same networking device so `localhost` would not connect. 

I _think_ you need to use the container name in place of `localhost`. Try `--execution-endpoint=http://geth:8551`. If that doesn't work, you might need to set the network_mode to host

**Comment by klestrong** [comment]
Thanks for the help!
I've tried putting them in the same docker network, like below, but still no go.  Also, this doesn't apply to the config in which I run Geth execution client and Beacon node on separate servers.  When on separate servers, I'm able to get a successful curl to the Geth execution client from the Beacon node.
```
        "Name": "go-ethereum-v11023_default",
        "Id": "88506b2222e2b49144fc1ba4cb1917dc913427c9f8c1c2d49a7cf7576cc41056",
        "Created": "2022-09-07T03:39:11.968289029-07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.29.0.0/16",
                    "Gateway": "172.29.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4bf8e50f03dd04516b09aa4801205555bbe95efe206a6d90822a38d33ee21b0e": {
                "Name": "go-ethereum-v11023_geth_1",
                "EndpointID": "f55ab6188b817201805a74e77956bc629e169c64b036c4e5e1f82229af550043",
                "MacAddress": "02:42:ac:1d:00:02",
                "IPv4Address": "172.29.0.2/16",
                "IPv6Address": ""
            },
            "91a9ac9be6b0c496ab3c22365da6012635e3e36738f45285e47e03a6e94541fd": {
                "Name": "beacon-node",
                "EndpointID": "b388a109a7e7d2157743a4cca26e44a39fe14ed0e9d1fae776a76c8399280c8a",
                "MacAddress": "02:42:ac:1d:00:03",
                "IPv4Address": "172.29.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "go-ethereum-v11023",
            "com.docker.compose.version": "1.29.2"
```
```
$ curl http://10.148.0.15:8545 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}'
{"jsonrpc":"2.0","id":67,"result":"Geth/v1.10.23-stable-d901d853/linux-amd64/go1.18"}
```

**Comment by klestrong** [comment]
Regarding your comment "--execution-endpoint=http://geth:8551".  I've tried that too.  I did the below on the Beacon node docker run specifying the Geth execution client name.  Still didn't work.  Could this be something other than connectivity?
```
--execution-endpoint=http://go-ethereum-v11023_geth_1:8551
```

**Comment by prestonvanloon** [comment]
Add these to geth, just to be sure
```
--authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts "*"
```

**Comment by majedtraboulsi** [comment]
@klestrong did the comment above resolve your issue? it did for me.

**Comment by aiji-nishijma** [comment]
I'm also stuck in a similar situation.

**Comment by alex-test-38** [comment]
I have the same issue and using host network mode can work it out. But I have no idea why Prysm beacon node cannot connect geth node under docker network settings.

**Comment by hiromaily** [comment]
I had a same issue but, fixed by using container name
```
  # this is my geth node in docker-compose
  execution:
    # https://hub.docker.com/r/ethereum/client-go/
    image: ethereum/client-go:v1.10.26
    container_name: execution
```
```
# options for beacon node
--execution-endpoint=http://execution:8551
```
