### ISSUE TITLE
Graffiti flag not work

### ISSUE THREAD

**Issue by 0xRook1e** [prysmaticlabs/prysm#11608]
# 🐞 Bug Report

### Description

I deployed a set in K8S with reference to the document, but Graffti did not take effect. I'm not sure if it is related to external signatures (we use Web3signer)

Here is my container args 
```
spec:
  containers:
  - args:
    - --datadir=/data/prysm
    - --accept-terms-of-use
    - --disable-rewards-penalties-logging
    - --disable-account-metrics
    - --prater
    - --config-file=/data/config.yaml
    - --validators-external-signer-url=http://web3-signer-prater-tls.web3-signer.svc.cluster.local/
    - --proposer-settings-file=/data/proposer.json
    - --graffiti=test
    - --beacon-rpc-provider=ethereum2-prater-beacon-prysm-staking.web3-helm.svc.cluster.local:4000
    - --monitoring-port=9090
    - --monitoring-host=0.0.0.0
```

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error
Container log 
```
time="2022-11-02 07:55:13" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x91b8b1caa8e1] slot=4238996 slotInEpoch=20 timeTillDuty=3m59s totalAttestersInEpoch=1
time="2022-11-02 07:59:16" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[392619] BeaconBlockRoot=0x8e47a41115c3 CommitteeIndex=1 Slot=4238996 SourceEpoch=132467 SourceRoot=0xbe34bd41aa99 TargetEpoch=132468 TargetRoot=0xb90779afbf1d prefix=validator
time="2022-11-02 08:01:36" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x91b8b1caa8e1] slot=4239032 slotInEpoch=24 timeTillDuty=4m48s totalAttestersInEpoch=1
time="2022-11-02 08:06:28" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[392619] BeaconBlockRoot=0xa7d8de3712d2 CommitteeIndex=16 Slot=4239032 
```
https://docs.prylabs.network/docs/prysm-usage/graffiti-file 
The log does not include Graffti. 

## 🌍  Your Environment

**Operating System:**
Kubernetes

**What version of Prysm are you running? (Which release)**

- gcr.io/prysmaticlabs/prysm/validator:v3.1.1
- gcr.io/prysmaticlabs/prysm/validator:v3.1.2 
- geth: v1.10.25
- web3Signer: consensys/web3signer:22.8.1-jdk11 
None of them work

Thank you very much for any help.
