### ISSUE TITLE
Timeout from http.Client

### ISSUE THREAD

**Issue by dzmitrykliapkou** [prysmaticlabs/prysm#11707]
# 🐞 Bug Report

### Description

Sometimes execution client drops behind the network and catches up very slowly. At the same time we see a lot of warnings in Prysm logs:
```
time="2022-11-30 07:46:16" level=warning msg="Skip processing batched blocks" error="could not process block in batch: timeout from http.Client: received an undefined ee error" prefix=initial-sync
time="2022-11-30 07:46:16" level=info msg="Processing block batch of size 63 starting from  0xc9c41c14... 5247329/5247529 - estimated time remaining 31s" blocksPerSecond=6.3 peers=48 prefix=initial-sync
time="2022-11-30 07:46:27" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-11-30 07:46:34" level=warning msg="Skip processing batched blocks" error="could not process block in batch: timeout from http.Client: received an undefined ee error" prefix=initial-sync
time="2022-11-30 07:46:34" level=info msg="Processing block batch of size 63 starting from  0xc9c41c14... 5247329/5247530 - estimated time remaining 31s" blocksPerSecond=6.3 peers=45 prefix=initial-sync
time="2022-11-30 07:46:41" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-11-30 07:46:46" level=info msg="Peer summary" activePeers=47 inbound=0 outbound=47 prefix=p2p
time="2022-11-30 07:46:55" level=warning msg="Execution client is not syncing" prefix=powchain
```

Troubleshooting docs say that "These errors are usually caused by invalid JWT configuration. If you're using HTTP-JWT to connect your EN-BN, ensure that both EN and BN are configured to use the same JWT secret. Different files are OK (eg when your EN and BN are on different machines), but the secret within each JWT file should be the same. See [Configure JWT authentication](https://docs.prylabs.network/docs/execution-node/authentication) for more information."

What might be the issue if both clients use the same JWT file? And despite these errors nodes slowly catch up the network - so it works

### Has this worked before in a previous version?

The same setup works on another Eth node - it has no issues with synchronization. The only difference is that problematic Eth node is archival one with gcmode set to archive

## 🔬 Minimal Reproduction

Here is our docker-compose.yml

```yaml
---
version: '3'
services:
  geth:
    image: ethereum/client-go:v1.10.26
    container_name: geth
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - /data/archive:/root/.ethereum
      - /data/node.toml:/root/.ethereum/node.toml
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --cache=8192
      - --maxpeers=10
      - --syncmode=full
      - --gcmode=archive
      - --snapshot=false
      - --config=/root/.ethereum/node.toml
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v3.1.2
    container_name: prysm
    depends_on:
      - geth
    restart: unless-stopped
    ports:
      - "3500:3500"
      - "8080:8080"
    volumes:
      - /datav2:/data
      - /data/archive/geth/jwtsecret:/tmp/jwtsecret:ro
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --datadir=/data
      - --execution-endpoint=http://geth:8551
      - --jwt-secret=/tmp/jwtsecret
      - --accept-terms-of-use
      - --rpc-host=0.0.0.0
      - --rpc-port=4000
      - --monitoring-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```

## 🌍  Your Environment

OS: Amazon Linux 2
HW: 4 vcpu, 32 GB RAM
Execution client: Geth `ethereum/client-go:v1.10.26`
Consensus client: Prysm `gcr.io/prysmaticlabs/prysm/beacon-chain:v3.1.2`
(Both running in Docker containers on the same machine)
