### ISSUE TITLE
Cant exit - "could not filter public keys for deletion"

### ISSUE THREAD

**Issue by nivshitrit** [prysmaticlabs/prysm#12197]
# 💎 Issue

trying to voluntary-exit my testnet validator, but it keeps throwing this error (at the bottom):

```
Select the account(s) on which you wish to perform a voluntary exit

  Done selecting

  All accounts

  0 | mentally-fair-sheep | 0xa8da34a718d1


--------- Account ----------

Name:        Done selecting

level=fatal msg="Could not perform voluntary exit" error="could not filter public keys for deletion: could not filter public keys for voluntary exit: ^D" prefix=accounts
```

### Background

im running this on k8s, i have an node running and i have multiple active validators hooked to that node from that same k8s cluster.
does anyone have any idea?
the relevant part from my k8s file:

```
containers:
        - args:
            - "accounts"
            - "voluntary-exit"
            - --beacon-rpc-provider=beacon-chain:4000
            - --wallet-dir=/data
            - --wallet-password-file=/passwords/password.txt
            - --goerli
            - --accept-terms-of-use
          image: gcr.io/prysmaticlabs/prysm/validator:latest
```

 Context and background information on the discussion...
