### ISSUE TITLE
Validator --show-deposit-data not working

### ISSUE THREAD

**Issue by radubuciuceanu** [prysmaticlabs/prysm#13609]
### Describe the bug

I have a 2 nodes POS private chain configured as [here](https://github.com/OffchainLabs/eth-pos-devnet) but adjusted to run on k8s. When I try to create a validator wallet on my second node, I have no way to get the deposit data and the withdrawal public key. Here is what the docs from [here](https://docs.prylabs.network/docs/wallet/deterministic) sais:

![image](https://github.com/prysmaticlabs/prysm/assets/39530866/12335dd2-931e-45e3-912f-452137f5b7e4)

And here is what I get in reality:

![image](https://github.com/prysmaticlabs/prysm/assets/39530866/bd7d149a-101b-4b87-949f-e6ed1f47a7ae)

### Has this worked before in a previous version?

```text
I don't know.
```

### 🔬 Minimal Reproduction

Taking this config file:
```yml
CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

DENEB_FORK_VERSION: 0x20000093

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 6

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
```

And having the consensus layer (prysm beacon-chain) and the execution layer (geth) running in the same k8s pod (meaning it's on the same localhost network).

1. Run `prysm validator --datadir ./ --chain-config-file ./consensus.config.yml wallet create --wallet-dir .`
2. Run `prysm validator --datadir . --chain-config-file ./consensus.config.yml accounts list --wallet-dir . --show-deposit-data`

### Error

```text
No withdrawal data being shown.
No deposit data being shown.
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v4.1.1

### Anything else relevant (validator index / public key)?

Can provide the genesis.json file as well if it's really needed.
