### ISSUE TITLE
Lighthouse CL < > Prysm VC incompatibility

### ISSUE THREAD

**Issue by barnabasbusa** [prysmaticlabs/prysm#13852]
### Describe the bug

We are in the process to test cross beacon <> validator client compatibility, and found a bug when testing nimbus CL with prysm VC. 

Prysm reports:
```sh
time="2024-04-05 12:15:11" level=info msg="Waiting for deposit to be observed by beacon node" prefix=client pubkey=0xa2e2d8384fc8 status="UNKNOWN_STATUS"
```

Lighthouse reports:
```sh
nothing out of the ordinary
```

Snooper between cl <> vc reports:
```json
Apr  5 12:15:47.524 2024 RESPONSE (status 200 OK) 
{
  "execution_optimistic": false,
  "finalized": false,
  "data": []
}

Apr  5 12:15:47.524 2024 REQUEST /eth/v1/node/version
null

Apr  5 12:15:47.524 2024 RESPONSE (status 200 OK) 
{
  "data": {
    "version": "Nimbus/v24.3.0-dc19b0-stateofus"
  }
}

Apr  5 12:15:59.523 2024 REQUEST /eth/v1/beacon/states/head/validators
{
  "ids": [
    "0xaaf6c1251e73fb600624937760fef218aace5b253bf068ed45398aeb29d821e4d2899343ddcbbe37cb3f6cf500dff26c",
    "0x8aa5bbee21e98c7b9e7a4c8ea45aa99f89e22992fa4fc2d73869d77da4cc8a05b25b61931ff521986677dd7f7159e8e6",
...
```

It seems like prysm is stuck on requesting genesis state, and stops there. 

### Expected behavior

I would expect all client combinations would work. 

### Steps to reproduce

config.yaml: 
```yaml
participants:
  - cl_type: lighthouse
    vc_type: prysm
additional_services:
  - dora
snooper_enabled: true
global_log_level: debug
```

`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file config.yaml`

### Additional context

[Current BN <> VC Compatibility list tracker](https://github.com/kurtosis-tech/ethereum-package?tab=readme-ov-file#beacon-node--validator-client-compatibility)

![Screenshot 2024-04-05 at 14 08 53](https://github.com/ChainSafe/lodestar/assets/21987084/4ba19a53-36d3-4d39-b563-3dc1f90b2fef)

**Comment by nflaig** [comment]
This is likely related to Prysm VC sending an empty statuses array in `POST /eth/v1/beacon/states/head/validators`

**Comment by barnabasbusa** [comment]
Looks like this issue is related to the fact that prysm vc can't find validators on chain:

```
time="2024-07-04 11:57:36" level=info msg="Waiting for deposit to be observed by beacon node" prefix=client pubkey=0xb9e03b94bb69 status="UNKNOWN_STATUS
```

**Comment by barnabasbusa** [comment]
Looks like using the latest versions, its looking even worse:
```
time="2025-03-26 11:43:30" level=error msg="error getting validator duties" error="failed to get duties for next epoch `1`: failed to get attester duties for epoch `1`: HTTP request unsuccessful (500: UNHANDLED_ERROR: UnableToReadSlot)" prefix=client
time="2025-03-26 11:43:30" level=error msg="Failed to update assignments" error="failed to get duties for next epoch `1`: failed to get attester duties for epoch `1`: HTTP request unsuccessful (500: UNHANDLED_ERROR: UnableToReadSlot)" prefix=client
time="2025-03-26 11:43:30" level=info msg="Starting health check routine for beacon node apis" prefix=client
time="2025-03-26 11:43:30" level=info msg="Event stream reconnecting..." prefix=client
time="2025-03-26 11:43:30" level=info msg="Starting event stream" prefix=client topics=[head]
time="2025-03-26 11:43:30" level=info msg="Listening to Beacon API events" topics=head
time="2025-03-26 11:43:30" level=fatal msg="Failed to update proposer settings" error="HTTP request unsuccessful (500: UNHANDLED_ERROR: UnableToReadSlot)" prefix=client
```
config to reproduce:
```yaml
participants:
  - el_type: geth
    el_image: ethereum/client-go:latest
    cl_type: lighthouse
    cl_image: sigp/lighthouse:latest-unstable
    vc_type: prysm
    vc_image: gcr.io/prysmaticlabs/prysm/validator:latest
    count: 1
network_params:
  genesis_delay: 120
  min_validator_withdrawability_delay: 1
  shard_committee_period: 1
  num_validator_keys_per_node: 250
  churn_limit_quotient: 16
additional_services:
  - assertoor
snooper_enabled: false
disable_peer_scoring: true
assertoor_params:
  image: "ethpandaops/assertoor:master"
  run_stability_check: false
  run_block_proposal_check: false
  tests:
    - https://raw.githubusercontent.com/ethpandaops/assertoor-test/5a9c3c0278e6cd977ec2ef56f4091fdce7e8b7f7/assertoor-tests/block-proposal-check.yaml
```
