### ISSUE TITLE
Prysm VC more robust content-type header handling

### ISSUE THREAD

**Issue by nflaig** [prysmaticlabs/prysm#14093]
### Describe the bug

Was looking into https://github.com/ChainSafe/lodestar/issues/6633 compatibility issue of Lodestar BN <> Prsym VC. 

The error on the Prysm side
```
time="2024-06-08 20:13:34" level=info msg="Syncing with beacon node to align on chain genesis info" prefix=client
time="2024-06-08 20:13:34" level=warning msg="Could not determine if beacon chain started" error="could not receive ChainStart from stream: failed to get genesis data: genesis data is nil: could not connect" prefix=client
```

But the response from Lodestar looks correct
```
time="2024-06-08T20:13:44Z" level=info msg="REQUEST #2: GET /eth/v1/beacon/genesis" length=0 type=json
time="2024-06-08T20:13:44Z" level=info msg="RESPONSE #2: GET /eth/v1/beacon/genesis" length=169 status=200 type=json
{
  "data": {
    "genesis_fork_version": "0x10000038",
    "genesis_time": "1717877689",
    "genesis_validators_root": "0x70498f18a6f07107a2a05d0d36c7cbd93b3e439023cbef21a6681eebee194526"
  }
}

```

I believe the reason why the data is `nil` is due to the way the content-type header is checked
https://github.com/prysmaticlabs/prysm/blob/8413660d5f4498beb4a91b3b609ae4d6daa7def6/validator/client/beacon-api/json_rest_handler.go#L112

it compares the whole header against the media type but in reality, the conten type header can also include the charset and boundry (see [Content-Type#directives](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#directives)).

Lodestar returns the following header
```
content-type: application/json; charset=utf-8
```
which is a valid content-type header format, on Prysm side you probably wanna apply something like
```go
strings.SplitN(contentType, ";", 2)[0]
```

### 🔬 Minimal Reproduction

Kurtosis config

```yaml
participants:
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: lodestar
    cl_image: chainsafe/lodestar:latest
    vc_type: prysm
    vc_image: gcr.io/prysmaticlabs/prysm/validator:latest
    count: 2
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: prysm
    cl_image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    vc_type: lodestar
    vc_image: chainsafe/lodestar:latest
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v5.0.3

### Anything else relevant (validator index / public key)?

Related issue https://github.com/ChainSafe/lodestar/issues/6633

**Comment by nflaig** [comment]
Another observation, you might not wanna return `nil` if status is 2xx but only if it's status 204 (no content).
https://github.com/prysmaticlabs/prysm/blob/8413660d5f4498beb4a91b3b609ae4d6daa7def6/validator/client/beacon-api/json_rest_handler.go#L113-L116

A 200 response without content type header, or unsupported media type in content type header could be explicitly handled which would result in an easier to debug error instead of `genesis data is nil`.

**Comment by james-prysm** [comment]
Thanks for the report will fix!

**Comment by nflaig** [comment]
All Lodestar <> Prysm issues seem to be resolved :tada:
![image](https://github.com/prysmaticlabs/prysm/assets/38436224/6af8731c-036b-4c1e-b838-9b75949bcf3a)

Running the following config
```yaml
participants:
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: lodestar
    cl_image: nflaig/lodestar:ignore-empty-statuses
    vc_type: prysm
    vc_image: ethpandaops/prysm-validator:develop-dfe31c9
    count: 2
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-dfe31c9
    vc_type: lodestar
    vc_image: nflaig/lodestar:ignore-empty-statuses
    vc_extra_params:
      - --http.requestWireFormat=ssz
    count: 2
```

I can also confirm that https://github.com/prysmaticlabs/prysm/pull/14075 works as expected, we can enable ssz-only mode on Lodestar with Prysm without any errors (as it falls back to JSON as expected now).

Just a quick side note, I noticed another issue that Prysm VC sends an empty statuses array when calling `POST /eth/v1/beacon/states/head/validators`. I would argue this is inline with the spec and I improved the handling on Lodestar side (https://github.com/ChainSafe/lodestar/pull/6876) but previously this would just result in returning no validators (irrespective of ids passed).
