### ISSUE TITLE
go build for minimal network preset misbehaves

### ISSUE THREAD

**Issue by barnabasbusa** [prysmaticlabs/prysm#14703]
### Describe the bug

Related [issue](https://github.com/prysmaticlabs/prysm/issues/14249).

If I build prysm with bazel it works correctly for mainnet and minimal preset. 
If I build prysm with go it works correctly only for mainnet preset. 

If I try to run prysm using go build environment (`go build -tags="--config=minimal,blst_enabled,blst_portable"`) I get the following error:
```
time="2024-12-09 10:08:23" level=warning msg="Running on custom Ethereum network specified in a chain configuration yaml file" prefix=flags
time="2024-12-09 10:08:23" level=warning msg="Using minimal config" prefix=node
....
time="2024-12-09 10:08:23" level=fatal msg="unable to start beacon node: could not start modules: could not start DB: could not load genesis from file: failed to unmarshal state, detected fork=deneb: incorrect size" prefix=main
```

Another weird observation is that if I use a minimal preset image (using go built) with mainnet network settings the process starts up, but crashes with segfault after about 30 seconds. 

segfault: 
```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe3d6e0]

goroutine 4918 [running]:
github.com/prysmaticlabs/prysm/v5/beacon-chain/forkchoice/doubly-linked-tree.(*Store).setOptimisticToInvalid(0x40001d6960, {0x23dcfd8, 0x4002e94b40}, {0xe4, 0xb7, 0x34, 0xdf, 0xf7, 0xf3, 0x61, ...}, ...)
	/opt/actions-runner/_work/eth-client-docker-image-builder/eth-client-docker-image-builder/source/beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go:26 +0x50
github.com/prysmaticlabs/prysm/v5/beacon-chain/forkchoice/doubly-linked-tree.(*ForkChoice).SetOptimisticToInvalid(0x2000?, {0x23dcfd8?, 0x4002e94b40?}, {0xe4, 0xb7, 0x34, 0xdf, 0xf7, 0xf3, 0x61, ...}, ...)
	/opt/actions-runner/_work/eth-client-docker-image-builder/eth-client-docker-image-builder/source/beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go:363 +0x5c
github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).notifyForkchoiceUpdate(0x4002e14200, {0x23dcfd8?, 0x4002e94b40?}, 0x400250e360)
	/opt/actions-runner/_work/eth-client-docker-image-builder/eth-client-docker-image-builder/source/beacon-chain/blockchain/execution_engine.go:93 +0xc58
github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).lateBlockTasks(0x4002e14200, {0x23dcfd8, 0x4002e94b40})
	/opt/actions-runner/_work/eth-client-docker-image-builder/eth-client-docker-image-builder/source/beacon-chain/blockchain/process_block.go:675 +0x9c4
github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).runLateBlockTasks(0x4002e14200)
	/opt/actions-runner/_work/eth-client-docker-image-builder/eth-client-docker-image-builder/source/beacon-chain/blockchain/process_block.go:486 +0x188
created by github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).Start in goroutine 4857
	/opt/actions-runner/_work/eth-client-docker-image-builder/eth-client-docker-image-builder/source/beacon-chain/blockchain/service.go:211 +0x140
```

### Has this worked before in a previous version?

```text
Not that I'm aware of.
```

### 🔬 Minimal Reproduction

kt config:
```yaml
participants:
  - cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-bazel-minimal-minimal-30a136f # This works
  - cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-go-minimal-minimal-linux-arm64-30a136f # This fails
network_params:
  preset: minimal
```

To repro the segfault
```yaml
participants:
  - cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-go-minimal-minimal-linux-arm64-30a136f # This should fail right away, but instead it segfaults
network_params:
  preset: mainnet
```

### Error

```text
Already shared above.
```

### Platform(s)

Mac (Apple Silicon)

### What version of Prysm are you running? (Which release)

latest develop commit 30a136f

### Anything else relevant (validator index / public key)?

N/A
