### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by tbenr** [prysmaticlabs/prysm#14892]
### Describe the bug

The crash isn't happening consistently but, when it happens is it on node startup

### Has this worked before in a previous version?

```text

```

### 🔬 Minimal Reproduction

```
participants_matrix:
  el:
    - el_type: geth
      el_image: ethpandaops/geth:prague-devnet-6
  cl:
    - cl_type: teku
      cl_image: consensys/teku:develop
      cl_extra_env_vars: {"JAVA_OPTS": "-Xmx3G -XX:UseSVE=0"}
    - cl_type: prysm
      cl_image: ethpandaops/prysm-beacon-chain:develop
      vc_image: ethpandaops/prysm-validator:develop
network_params:
  num_validator_keys_per_node: 32
  electra_fork_epoch: 100
additional_services:
  - dora
snooper_enabled: true
```

### Error

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x35dac40]

goroutine 4652 [running]:
github.com/prysmaticlabs/prysm/v5/beacon-chain/forkchoice/doubly-linked-tree.(*Store).setOptimisticToInvalid(0x400015c960, {0x1b70970, 0x4001edf0e0}, {0xca, 0xe0, 0x56, 0xb6, 0xa3, 0x4c, 0x88, ...}, ...)
        beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go:26 +0x50
github.com/prysmaticlabs/prysm/v5/beacon-chain/forkchoice/doubly-linked-tree.(*ForkChoice).SetOptimisticToInvalid(0x4001468118?, {0x1b70970?, 0x4001edf0e0?}, {0xca, 0xe0, 0x56, 0xb6, 0xa3, 0x4c, 0x88, ...}, ...)
        beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go:363 +0x5c
github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).notifyForkchoiceUpdate(0x400030a400, {0x1b70970?, 0x4001edf0e0?}, 0x4003c979e0)
        beacon-chain/blockchain/execution_engine.go:93 +0xc10
github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).lateBlockTasks(0x400030a400, {0x1b70970, 0x4001edf0e0})
        beacon-chain/blockchain/process_block.go:678 +0x9a0
github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).runLateBlockTasks(0x400030a400)
        beacon-chain/blockchain/process_block.go:494 +0x184
created by github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).Start in goroutine 4939
        beacon-chain/blockchain/service.go:217 +0x13c
```
