### ISSUE TITLE
info msg="Waiting for beacon node to sync to latest chain head" prefix=client

### ISSUE THREAD

**Issue by Jo-Shino** [prysmaticlabs/prysm#15059]
### Describe the bug

Hi,

I am currently trying to create a PoS private network on my local PC using geth and prysm. I am working with the following articles. But unlike the article, **I am using Docker and running geth, prysm and validator on the supervisord.**
[https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet](https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet)

And I am trying to create a private PoS chain with two nodes (node1 and node2) by activating two full nodes with geth, prysm and validator software in Docker.

The first node (geth+prysm+validator) was successfully started, but the second node is not synchronizing and getting block information from node1. Below are the logs for node1 and node2, I have started each node with docker using supervisisord. Node2's log shows info **msg=“Waiting for beacon node to sync to latest chain head” prefix= client”** in the log. 

How can I solve the problem?

<img width="1144" alt="Image" src="https://github.com/user-attachments/assets/4692b33f-6656-44e3-9a13-2d9f09f29868" />

<img width="1140" alt="Image" src="https://github.com/user-attachments/assets/defad6ed-4dff-493f-b035-472a0d44edd7" />

### Has this worked before in a previous version?

```text

```

### 🔬 Minimal Reproduction

1. docker-compose build node1 --no-cache
First build node1.
```
docker-compose build node1 --no-cache
```
2. docker-compose up node1 -d
```
docker-compose up node1 -d
```
3. Find node1's enode for node2's geth and node1's ip4 address for node2's prysm
```
docker exec -it eth-node1 geth attach /data/geth/geth.ipc  
```
After entering the geth console, execute the following command.
```
> admin.nodeInfo.enode
"enode://~~~~~~~@127.0.0.1:30303"
```
Then run the following command to get the ip4 address.
```
docker exec eth-node1 curl localhost:3500/eth/v1/node/identity

{"data":{"peer_id":"~~~","enr":"enr:〇〇〇〇","p2p_addresses":["/ip4/172.18.0.2/tcp/13000/p2p/~~~","/ip4/172.18.0.2/udp/13000/quic-v1/p2p/---------"],"discovery_addresses":["/ip4/172.18.0.2/udp/12000/p2p/~~~"],"metadata":{"seq_number":"2","attnets":"---"}}}
```
Note the ip4 in the “/ip4/172.18.0.2/tcp/13000/p2p/~~~” section.

4. Pass node1's enode value to “--bootnode” which is the startup flag of node2's geth. Also pass node1's ip4 address value to "--peer" which is the startup flag of node2's prysm.

The below file is supervisord.node2.conf which is called when node2 is started.

And **--bootnodes “enode://~~~~~@172.18.0.2:30303”**, **--peer=“/ip4/172.18.0.2/tcp/13000/p2p/~~~”/** is where the enode and ip4 values are assigned.
```
[supervisord]
nodaemon=true
user=root
loglevel=debug

[program:geth]
command=/usr/local/bin/geth --http --http.api eth,net,web3 /
--ws --ws.api eth,net,web3 --authrpc.jwtsecret /config/jwt.hex /
--datadir /data/geth --syncmode full --allow-insecure-unlock /
--unlock 0x123463a4b065722e99115d6c222f267d9cabb524 /
--password /config/secret.txt --port 30304 --discovery.port 30304 /
**--bootnodes "enode://~~~~~@172.18.0.2:30303"**
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:beacon-chain]
command=/usr/local/bin/beacon-chain --datadir /data/beacon /
--min-sync-peers 1 --genesis-state /config/genesis/genesis.ssz /
--bootstrap-node= --interop-eth1data-votes --chain-config-file /config/config.yml /
--contract-deployment-block 0 --chain-id 32382 /
--accept-terms-of-use --jwt-secret /config/jwt.hex /
--suggested-fee-recipient 0x123463a4B065722E99115D6c222f267d9cABb524 /
--minimum-peers-per-subnet 0 --enable-debug-rpc-endpoints /
--execution-endpoint /data/geth/geth.ipc /
**--peer="/ip4/172.18.0.2/tcp/13000/p2p/~~~"/**
 --p2p-udp-port 12001 --p2p-tcp-port 13001 /
--grpc-gateway-port 3501 --rpc-port 4001
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2
startsecs=60
startretries=3

[program:validator]
command=/usr/local/bin/validator --datadir /data/validator /
--accept-terms-of-use --interop-num-validators 64 /
--chain-config-file /config/config.yml /
--beacon-rpc-provider localhost:4001
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=3
startsecs=60
startretries=3
```

The following is the supervisord.conf used to start node1.
```
[supervisord]
nodaemon=true
user=root
loglevel=debug

[program:geth]
command=/usr/local/bin/geth --http --http.api eth,net,web3 /
--ws --ws.api eth,net,web3 --authrpc.jwtsecret /config/jwt.hex /
--datadir /data/geth --syncmode full /
--allow-insecure-unlock --unlock 0x123463a4b065722e99115d6c222f267d9cabb524 /
--password /config/password.txt
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:beacon-chain]
command=/usr/local/bin/beacon-chain --datadir /data/beacon /
--min-sync-peers 0 --genesis-state /config/genesis/genesis.ssz /
--bootstrap-node= --interop-eth1data-votes --chain-config-file /config/config.yml /
--contract-deployment-block 0 --chain-id 32382 --accept-terms-of-use /
--jwt-secret /config/jwt.hex --suggested-fee-recipient 0x123463a4B065722E99115D6c222f267d9cABb524 /
--minimum-peers-per-subnet 0 --enable-debug-rpc-endpoints /
--execution-endpoint /data/geth/geth.ipc --rpc-port 4000 /
--grpc-gateway-port 3500
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2
startsecs=60
startretries=3

[program:validator]
command=/usr/local/bin/validator --datadir /data/validator --accept-terms-of-use /
--interop-num-validators 64 --chain-config-file /config/config.yml /
--beacon-rpc-provider localhost:4000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=3
startsecs=60
startretries=3
```

The below file is docker-compose.yml.
```
version: '3.8'

services:
  node1:
    container_name: eth-node1
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      devnet:
        ipv4_address: 172.18.0.2
    volumes:
      - ./data/node1:/data
      - ./config:/config
      - shared_genesis:/config/genesis
    ports:
      - "8545:8545"  # geth HTTP
      - "8546:8546"  # geth WS
      - "3500:3500"  # prysm HTTP
      - "13000:13000" # p2p

  node2:
    container_name: eth-node2
    build:
      context: .
      dockerfile: Dockerfile.node2
    networks:
      devnet:
        ipv4_address: 172.18.0.3
    volumes:
      - ./data/node2:/data
      - ./config:/config
      - shared_genesis:/config/genesis:ro
    ports:
      - "8547:8545"  # geth HTTP
      - "8548:8546"  # geth WS
      - "3501:3500"  # prysm HTTP
      - "13001:13000" # p2p

volumes:
  shared_genesis:

networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

```

### Error

```text
2025-03-17 11:50:19,502 DEBG 'validator' stderr output:
2025-03-17 20:50:19 time="2025-03-17 11:50:19" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=client
2025-03-17 20:50:19 
2025-03-17 20:50:20 2025-03-17 11:50:20,757 DEBG 'geth' stderr output:
2025-03-17 20:50:20 INFO [03-17|11:50:20.757] Looking for peers                        peercount=1 tried=25 static=0
2025-03-17 20:50:20 
2025-03-17 20:50:25 2025-03-17 11:50:25,365 DEBG 'beacon-chain' stderr output:
2025-03-17 20:50:25 time="2025-03-17 11:50:25" level=warning msg="Execution client is not syncing" prefix=execution
2025-03-17 20:50:25 time="2025-03-17 11:50:25" level=error msg="Beacon node is not respecting the follow distance. EL client is syncing." lastBlockNumber=0 prefix=execution
```
