### ISSUE TITLE
Keymanager passphrase with special characters cannot be parsed 

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#4686]
I'm passing keystore parameters to the validator in the following way:
```
--keymanager=keystore
--keymanageropts="{'path':'/etc/validators','passphrase':\"$(KEYSTORE_PASSWORD)\"}"
```
When I start the validator, I get the following output:
```
The keystore key manager generates keys and stores them in a local encrypted store.  The options are:
  - path This is the filesystem path to where keys will be stored.  Defaults to the user's home directory if not supplied
  - passphrase This is the passphrase used to encrypt keys.  Will be asked for if not supplied
A sample set of options are:
  {
    "path":   "/home/me/keys", // Store the keys in '/home/me/keys'
    "passphrase": "secret"     // Use the passphrase 'secret' to encrypt and decrypt keys
  }
time="2020-01-28 20:00:49" level=error msg="invalid character 'G' after top-level value" prefix=main
```

Latest commit: `3e9bf58d81a986881de9d2d0fcbe565b3fe83ef2`

**Comment by mcdee** [comment]
Can you try this with:

```
--keymanageropts='{"path":"/etc/validators","passphrase":"'"${KEYSTORE_PASSWORD}"'"}'

```

**Comment by tsudmi** [comment]
@mcdee thanks for the reply.

In such case I'm getting:
```
time="2020-01-29 19:33:08" level=error msg="invalid character '\'' looking for beginning of value" prefix=main
```

**Comment by mcdee** [comment]
Please could you paste your entire command line?  I just double-checked and the above works on my local machine.

**Comment by tsudmi** [comment]
Hi @mcdee ,
I'm running the validator in Kubernetes, so I have to pass these parameters in `yaml` file.
Here is a snippet of the POD container:
```yaml
- name: validator
   image: "gcr.io/prysmaticlabs/prysm/validator:latest"
   imagePullPolicy: Always
   args:
     - --monitoring-port=9090
     - --datadir=/data
     - --keymanager=keystore
     - --keymanageropts="{'path':'/etc/validators','passphrase':\"$(KEYSTORE_PASSWORD)\"}"
   env:
     - name: KEYSTORE_PASSWORD
       value: "some_long_and_complex_password"
```
@prestonvanloon did you manage to pass those parameters inside your deployment files?
