### ISSUE TITLE
Specifying --wallet-dir on restore doesn't work

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6799]
# 🐞 Bug Report

### Description

create-account.yaml:
```
...
        validator-restore-wallet:
                container_name: validator-restore-wallet
                image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
                command: validator wallet-v2 recover --menmonic-phrase="${RECOVER_WALLET_SEED}" --wallet-dir=/data
                volumes:
                        - ./validator:/data
```

Didn't work with `--wallet-dir="/data"` either.

### Has this worked before in a previous version?

No

## 🔥 Error

```
# docker-compose -f create-account.yaml run validator-restore-wallet
Enter a wallet directory (default: /home/.eth2validators/prysm-wallet-v2):
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

https://github.com/stefa2k/prysm-docker-compose with docker tag `HEAD-f414cf`
