### ISSUE TITLE
Wallet directory content on wallet restore

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6802]
# 🐞 Bug Report

### Description

```
...
        validator-restore-wallet:
                container_name: validator-restore-wallet
                image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
                command: validator wallet-v2 recover --menmonic-phrase="${RECOVER_WALLET_SEED}"
                volumes:
                        - ./validator:/data
```

Content should be allowed in wallet directory on `recover`. Use case: I already have 2 other wallets and want to recover a new one and make it my third one.

### Has this worked before in a previous version?

No

## 🔥 Error

```
# docker-compose -f create-account.yaml run validator-restore-wallet
Enter a wallet directory (default: /home/.eth2validators/prysm-wallet-v2):
/data
[2020-07-31 08:27:35] FATAL node: Could not open wallet: could not read keymanager kind for wallet: .gitignore is not an allowed keymanager
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

https://github.com/stefa2k/prysm-docker-compose with docker tag `HEAD-f414cf`
