### ISSUE TITLE
Infinite sync looping after 'incorrect proposer index' warning and `context canceled' error

### ISSUE THREAD

**Issue by HeikoAydt** [prysmaticlabs/prysm#7498]
# 🐞 Bug Report

### Description
The problem occurs when using Prysm as beacon node and [Vouch](https://github.com/attestantio/vouch) as validator client. After an `incorrect proposer index` warning, beacon node falls behind and has to be synced again. Sync process starts but then jumps back to earlier blocks to sync from and never finishes / keeps going in a loop.

### Has this worked before in a previous version?
Not that I am aware of.

## 🔬 Minimal Reproduction
Run Prysm:
```
bazel run //beacon-chain -- --medalla --p2p-host-ip $(curl -s v4.ident.me) --p2p-tcp-port=9002 --p2p-udp-port=9002 --rpc-host=127.0.0.1 --rpc-port=4002 --datadir=/home/heiko/prysm-datastore --http-web3provider=http://ETH1-ADDRESS:8545 > $HOME/log.prysm.beacon 2>&1
```

Run Vouch:
```
vouch --base-dir=$HOME/vouch
```

Vouch.yml:
```
beacon-node-address: localhost:4002
accountmanager:
  dirk:
    endpoints:
      - ADRESS_TO_DIRK:9091
    client-cert: file:///home/heiko/vouch/client-medalla-1.crt
    client-key: file:///home/heiko/vouch/client-medalla-1.key
    ca-cert: file:///home/heiko/vouch/ca.crt
    accounts:
      - ACCOUNTS...
submitter:
  style: all
  beacon-node-addresses:
    - localhost:4002
strategies:
  beaconblockproposal:
    style: best
    beacon-node-addresses:
      - localhost:4002
```

## 🔥 Error

<pre><code>
time="2020-10-11 16:44:26" level=warning msg="Incorrect proposer index" blockSlot=490721 error=<nil> prefix=sync
time="2020-10-11 16:54:02" level=info msg="Fallen behind peers; reverting to initial sync to catch up" currentEpoch=15336 peersEpoch=15336 prefix=sync syncedEpoch=15334
time="2020-10-11 16:54:02" level=error msg="context canceled" prefix=initial-sync
</code></pre>

This is followed by a number of 'Peer disconnected' / 'Peer connected' messages. Then the the sync process starts:

<pre><code>
time="2020-10-11 18:13:01" level=info msg="Processing block 0xdf7241fc... 490784/491164 - estimated time remaining 1m7s" blocksPerSecond=5.7 peers=30 prefix=initial-sync
time="2020-10-11 18:13:01" level=info msg="Processing block 0x97963b05... 490816/491164 - estimated time remaining 51s" blocksPerSecond=6.8 peers=30 prefix=initial-sync
time="2020-10-11 18:13:02" level=info msg="Processing block 0x3ee0ca80... 490880/491164 - estimated time remaining 31s" blocksPerSecond=8.9 peers=30 prefix=initial-sync
...
</code></pre>

After a short while another 'Peer disconnected' message is logged and the sync process starts from the same block:
<pre><code>
...
time="2020-10-11 18:13:09" level=info msg="Processing block 0xd19a5d37... 491040/491165 - estimated time remaining 4s" blocksPerSecond=26.0 peers=30 prefix=initial-sync
time="2020-10-11 18:13:09" level=info msg="Processing block 0x7ff54a7b... 491072/491165 - estimated time remaining 3s" blocksPerSecond=26.8 peers=30 prefix=initial-sync
time="2020-10-11 18:13:17" level=info msg="Peer disconnected" activePeers=29 multiAddr="/ip4/123.177.5.130/tcp/61188/p2p/16Uiu2HAm5qtqQCeBCcDqQ69kqLdQdQJpumMmHYjNRx96U1S2yVFU" prefix=p2p
time="2020-10-11 18:13:19" level=info msg="Processing block 0xdf7241fc... 490784/491165 - estimated time remaining 13s" blocksPerSecond=27.6 peers=29 prefix=initial-sync
time="2020-10-11 18:13:19" level=info msg="Processing block 0x97963b05... 490816/491165 - estimated time remaining 12s" blocksPerSecond=28.6 peers=29 prefix=initial-sync
...
</code></pre>

This keeps looping ad infinitum as far as I can tell. It never seems to reach the head again. The only way to fix it is to restart the beacon node.

## 🌍  Your Environment

**Operating System:**
Ubuntu-20.04 LTS

**What version of Prysm are you running? (Which release)**
[4c09e59b3b0a88eec08990f77645217573ff04eb](https://github.com/prysmaticlabs/prysm/commit/4c09e59b3b0a88eec08990f77645217573ff04eb)

**Anything else relevant (validator index / public key)?**
