### ISSUE TITLE
Validator: Could not submit attestation to beacon node - context deadline exceeded

### ISSUE THREAD

**Issue by littleskunk** [prysmaticlabs/prysm#7650]
# 🐞 Bug Report

### Description

Validator keeps losing ETH balance.
```
time="2020-10-27 11:36:56" level=info msg="Attestation schedule" attesters=1 prefix=validator pubKeys=[0x84057b23e0ed] slot=604388
time="2020-10-27 11:36:56" level=info msg="Attestation schedule" attesters=1 prefix=validator pubKeys=[0xad34771bb294] slot=604405
time="2020-10-27 11:37:52" level=error msg="Could not submit slot signature to beacon node: rpc error: code = Internal desc = Could not find attestation for slot and committee in pool" prefix=validator slot=604388
time="2020-10-27 11:37:56" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x84057b23e0ed slot=604388
time="2020-10-27 11:41:20" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xad34771bb294 slot=604405
```

This behavior stops as soon as I stop the slasher. The behavior comes back as soon as I start the slasher.
```
time="2020-10-27 12:15:20" level=info msg="Attestation schedule" attesters=1 prefix=validator pubKeys=[0x84057b23e0ed] slot=604577
time="2020-10-27 12:15:20" level=info msg="Attestation schedule" attesters=1 prefix=validator pubKeys=[0xad34771bb294] slot=604589
time="2020-10-27 12:15:40" level=info msg="Submitted new attestations" AggregatorIndices=[75711] AttesterIndices=[75711] BeaconBlockRoot=0xab9b2ddc99a2 CommitteeIndex=2 Slot=604577 SourceEpoch=15705 SourceRoot=0x66ba71dfb29b TargetEpoch=18893 TargetRoot=0x0d94d8ec8908 prefix=validator
time="2020-10-27 12:18:00" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[75710] BeaconBlockRoot=0xcf8320b11d0f CommitteeIndex=16 Slot=604589 SourceEpoch=15705 SourceRoot=0x66ba71dfb29b TargetEpoch=18893 TargetRoot=0x0d94d8ec8908 prefix=validator
```

### Has this worked before in a previous version?

Since a few releases, my validators are failing for different errors. Yes it has worked a few releases ago but I can't say which version it was.

## 🔬 Minimal Reproduction

```
services:
  beacon:
    depends_on:
      - geth
    restart: unless-stopped
    user: 993:991
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    volumes:
      - /mnt/ssd/eth/prysm-beacon:/data
    command:
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --accept-terms-of-use
      - --http-web3provider=http://geth:8545
      - --head-sync
      - --wait-for-synced
      - --medalla
  validator:
    depends_on:
      - beacon
    restart: unless-stopped
    user: 993:991
    ports:
      - 4242:4242
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    volumes:
      - /mnt/ssd/eth/prysm-wallet-v2:/wallet
      - /mnt/ssd/eth/prysm-validator:/validatorDB
    command:
      - --beacon-rpc-provider=beacon:4000
      - --monitoring-host=0.0.0.0
      - --accept-terms-of-use
      - --wallet-dir=/wallet
      - --wallet-password-file=/wallet/password.txt
      - --datadir=/validatorDB
      - --wait-for-synced
      - --medalla
  slasher:
    depends_on:
      - beacon
    restart: unless-stopped
    user: 993:991
    image: gcr.io/prysmaticlabs/prysm/slasher:stable
    volumes:
      - /mnt/ssd/eth/prysm-slasher:/data
    command:
      - --accept-terms-of-use
      - --beacon-rpc-provider=beacon:4000
      - --monitoring-host=0.0.0.0
      - --datadir=/data
      - --medalla
```

## 🔥 Error

See the error messages in the description above.

## 🌍  Your Environment

**Operating System:**

OpenMediaVault (debian)

**What version of Prysm are you running? (Which release)**

```
# docker run --rm gcr.io/prysmaticlabs/prysm/beacon-chain:stable --version
beacon-chain version Prysm/v1.0.0-beta.0.rc/a73c539fabc7974ade8e88d687150e8f59b7a262. Built at: 2020-10-24 17:00:19+00:00
# docker run --rm gcr.io/prysmaticlabs/prysm/validator:stable --version
validator version Prysm/v1.0.0-beta.0.rc/a73c539fabc7974ade8e88d687150e8f59b7a262. Built at: 2020-10-24 16:50:30+00:00
# docker run --rm gcr.io/prysmaticlabs/prysm/slasher:stable --version
hash slinging slasher version Prysm/v1.0.0-beta.0.rc/a73c539fabc7974ade8e88d687150e8f59b7a262. Built at: 2020-10-24 16:59:17+00:00
```

**Anything else relevant (validator index / public key)?**
