### ISSUE TITLE
Load graffiti from file and select different graffiti per validator 

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#8037]
# 🚀 Feature Request

### Description

Many users have requested this feature where they could use different graffiti for different validators running in the same client.

Reasons may include:
- Privacy (same graffiti may link validators)
- Fun (graffiti wall, etc)

### Describe the solution you'd like

New validator flag: `--graffiti-file=/path/to/graffitis.yaml`

Support for a yaml or JSON mapping that supports the following field types:
- validator index
- validator pubkey (or partial pubkey)
- validator pet-name
- default option or random array option (in place of default)

```yaml
# /path/to/graffitis.yaml
555: What's up I'm validator 555
1234: yolo
0x0abcef: Partial pubkey match
perfectly-unique-kingfish: My pet name is perfectly-unique-kingfish

# default OR random could be used
default: Mr F was here 
random:
- Mr A was here
- Mr B was here
- Mr C was here
- graffitiwall:0:0:#000000 
- graffitiwall:1:0:#000000 
```

### Describe alternatives you've considered

There is no alternative for this with a single validator client. 
A user would have to run a validator client for each key which complicates their infrastructure and can lead to other issues.
