### ISSUE TITLE
Failed to save span map to db on cache eviction: could not cast key and value into needed types

### ISSUE THREAD

**Issue by Ripolin** [prysmaticlabs/prysm#8709]
# 🐞 Bug Report

### Description

Since version 1.3.4 I see this error on my slasher :

```
time="2021-04-05 10:49:16" level=error msg="Failed to save span map to db on cache eviction: could not cast key and value into needed types" prefix=db
```

I have to restart slasher to make it disappear for a while. 

## 🌍  Your Environment

**Operating System:**

* Ubuntu 20.04 focal
* 12 vcores
* 32 GB ram

**What version of Prysm are you running? (Which release)**

* v1.3.5

**Anything else relevant (validator index / public key)?**

I use docker swarm to run a eth2 stack (validator, beacon and slasher). Docker daemon version is 20.15.5 and config for my slasher is :

```yaml
  slasher:
      image: gcr.io/prysmaticlabs/prysm/slasher:v1.3.5
      command:
      - --accept-terms-of-use
      - --beacon-rpc-provider=beacon_node:4000
      - --datadir=/root/.slasher
      - --rpc-host=0.0.0.0
      volumes:
      - slasher_datadir:/root/.slasher
```

Futhermore I use ```tuned-adm``` with profile ```network-latency```.
